# Generated by Django 3.0.4 on 2020-04-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(unique=True)),
                ('canvas_image', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
