# Generated by Django 3.0.4 on 2020-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedata',
            name='bg_images',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
