# Generated by Django 3.0.4 on 2020-04-12 13:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('remoteApp', '0003_auto_20200412_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagedata',
            name='the_json',
        ),
        migrations.AlterField(
            model_name='pagedata',
            name='bg_images',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='pagedata',
            name='canvas_image',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='pagedata',
            name='text',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
