# Generated by Django 3.0.4 on 2020-04-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remoteApp', '0004_auto_20200412_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagedata',
            old_name='bg_images',
            new_name='bg',
        ),
        migrations.RenameField(
            model_name='pagedata',
            old_name='canvas_image',
            new_name='canvas',
        ),
    ]
