# Generated by Django 3.0.4 on 2020-04-13 07:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('remoteApp', '0005_auto_20200412_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedata',
            name='action_pattern',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
